import { createTheme, ITheme } from "@fluentui/react";

export const docuIdTheme: ITheme = createTheme({
  palette: {
    themePrimary: "#005fb8",
    themeLighterAlt: "#f2f8fd",
    themeLighter: "#cce3f5",
    themeLight: "#a3ccec",
    themeTertiary: "#5a9dd8",
    themeSecondary: "#1f74c6",
    themeDarkAlt: "#0056a6",
    themeDark: "#00498c",
    themeDarker: "#003567",
    neutralLighterAlt: "#faf9f8",
    neutralLighter: "#f3f2f1",
    neutralLight: "#edebe9",
    neutralQuaternaryAlt: "#e1dfdd",
    neutralQuaternary: "#d0d0d0",
    neutralTertiaryAlt: "#c8c6c4",
    neutralTertiary: "#a19f9d",
    neutralSecondary: "#605e5c",
    neutralPrimaryAlt: "#3b3a39",
    neutralPrimary: "#323130",
    neutralDark: "#201f1e",
    black: "#000000",
    white: "#ffffff",
  },
  semanticColors: {
    buttonBackground: "#005fb8",
    buttonBackgroundHovered: "#0067c0",
    buttonBackgroundPressed: "#004c8c",
    buttonText: "#ffffff",
    inputBackground: "#ffffff",
    inputBorder: "rgba(0, 0, 0, 0.0578)",
    inputBorderHovered: "rgba(0, 0, 0, 0.0578)",
    inputFocusBorderAlt: "#005fb8",
  },
});
